name: Scheduler Preview
on:
  push:
    branches:
      - preview
  workflow_dispatch:
    branches:
      - preview
    inputs:
      note:
        description: "Note"
        required: false
        default: ""

concurrency: "preview"

jobs:
  master:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    name: Earning Scheduler Preview
    steps:
      - uses: actions/checkout@v4
        with:
          ref: preview
          fetch-depth: 0
          token: ${{ secrets.GH_AUTOMATION_TOKEN }}

      - name: Update data
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
        run: |
          yarn install
          NODE_ENV=development yarn fetch-data

      - name: Deploy to Cloudflare Pages
        id: cloudflare_deployment
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "sw-static-cache"
          gitHubToken: ${{ secrets.GH_AUTOMATION_TOKEN }}
          branch: preview
          directory: "./data"
          wranglerVersion: "3"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Scheduler
          author_email: scheduler@github.io
          message: "[CI Skip] Update earning data (preview)"
